p

diff --git a/jenkins-files/deployments/Jenkinsfile b/jenkins-files/deployments/Jenkinsfile
--- a/jenkins-files/deployments/Jenkinsfile
+++ b/jenkins-files/deployments/Jenkinsfile
@@ -49,14 +49,18 @@ pipeline {
         }
             steps {
             sh '''
-                    echo "Deploying to public instances..."
-                    INSTANCE_IDS=$(aws ec2 describe-instances \
-                        --filters "Name=tag:Role,Values=${WEB_TAG}" "Name=instance-state-name,Values=running" \
-                        --query "Reservations[].Instances[].InstanceId" \
-                        --region ${AWS_DEFAULT_REGION} \
-                        --output text)
+                    INSTANCE_ID=$(aws elbv2 describe-target-health \
+                    --target-group-arn arn:aws:elasticloadbalancing:us-east-2:568298704568:targetgroup/public-tg/6a8c122b802f3972 \
+                    --query 'TargetHealthDescriptions[?TargetHealth.State==`healthy`].Target.Id | [0]' \
+                    --output text)
 
+                    if [ -z "$INSTANCE_ID" ] || [ "$INSTANCE_ID" = "None" ]; then
+                    echo "ERROR: No healthy instances found in target group"
+                    exit 1
+                    fi
 
+                    echo  "Using instance: $INSTANCE_ID"
+                    
                     aws ssm send-command \
                          --instance-ids "$INSTANCE_ID" \
                          --document-name "AWS-RunShellScript" \
@@ -66,13 +70,6 @@ pipeline {
                          \"/home/ubuntu/nginx-deploy.sh\"
                          ]" \
                          --region ${AWS_DEFAULT_REGION}
-  
-                    aws ssm send-command \
-                        --targets $(echo $INSTANCE_IDS | sed 's/[^ ]*/Key=InstanceIds,Values=&/g' | sed 's/ / /g') \
-                        --document-name "AWS-RunShellScript" \
-                        --comment "Deploy to web tier" \
-                        --parameters 'commands=["sudo chmod +x nginx-deploy.sh", "./nginx-deploy.sh"]' \
-                        --region ${AWS_DEFAULT_REGION}
                 '''
             }
         }
@@ -120,10 +117,8 @@ pipeline {
                     exit 1
                     fi
 
-    echo "Using instance: $INSTANCE_ID"
+                    echo  "Using instance: $INSTANCE_ID"
                     
-
-
                     aws ssm send-command \
                          --instance-ids "$INSTANCE_ID" \
                          --document-name "AWS-RunShellScript" \
@@ -133,10 +128,6 @@ pipeline {
                          \"/home/ubuntu/python-deploy.sh\"
                          ]" \
                          --region ${AWS_DEFAULT_REGION}
-
-
-
-
                 '''
         }
     }
